/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mychat.tcp.login;

import mychat.tcp.gui.MyChatServerGUI;
import static mychat.tcp.gui.MyChatServerGUI.registeredUserList;

/**
 *
 * @author giacomo.pizzini
 */
public class loginUtentiGUI extends javax.swing.JFrame {

    /**
     * Creates new form loginUtentiGUI
     */
    public String userName = "";
    public String password = "";

    public loginUtentiGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        user_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        userName_text = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        password_text = new javax.swing.JPasswordField();
        register = new javax.swing.JButton();
        showPassword = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        user_label.setText("User Name:");

        password_label.setText("Password:");

        userName_text.setPreferredSize(new java.awt.Dimension(42, 24));
        userName_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userName_textKeyReleased(evt);
            }
        });

        submit.setText("Login");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        message.setLabelFor(message);
        message.setText("Error message");
        message.setVisible(false);
        message.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        message.setName("message"); // NOI18N

        password_text.setPreferredSize(new java.awt.Dimension(42, 24));
        password_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                password_textKeyReleased(evt);
            }
        });

        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        showPassword.setText("Show");
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("MyChat ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(message)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password_label)
                            .addComponent(user_label))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(96, 96, 96))
                            .addComponent(password_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(userName_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(showPassword)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(register)
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_label)
                    .addComponent(userName_text, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password_text, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(password_label)
                        .addComponent(showPassword)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPassword)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register)
                    .addComponent(submit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(message)
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        userName = userName_text.getText();
        password = password_text.getText();
        if(userName_text.getText().trim().isEmpty() && password_text.getText().isEmpty()){
            jLabelUsername.setText("Username is empty");
            jLabelPassword.setText("Password is empty");
        }else if(userName_text.getText().trim().isEmpty()){
            jLabelUsername.setText("Username is empty");
        }else if(password_text.getText().isEmpty()){
            jLabelPassword.setText("Password is empty");
        }else{
            boolean loggato = loginUtenti.login(userName, password);
            if (loggato == true) {
                //esegui chat
                new mychat.tcp.gui.MyChatClientGUI(userName).setVisible(true);
                //mychat.tcp.gui.MyChatClientGUI.setUserName(userName);
                dispose();
            } else {
                message.setVisible(true);
                message.setText("Incorrect password or username.");
            }
        }
    }//GEN-LAST:event_submitActionPerformed

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        if (!showPassword.isSelected()) {
            password_text.setEchoChar('*');
        } else {
            password_text.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_showPasswordActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        userName = userName_text.getText();
        password = password_text.getText();
        if(userName_text.getText().trim().isEmpty() && password_text.getText().isEmpty()){
            jLabelUsername.setText("Username is empty");
            jLabelPassword.setText("Password is empty");
        }else if(userName_text.getText().trim().isEmpty()){
            jLabelUsername.setText("Username is empty");
        }else if(password_text.getText().isEmpty()){
            jLabelPassword.setText("Password is empty");
        }else{
        String out = loginUtenti.register(userName, password);
        message.setVisible(true);
        message.setText(out);
        userName_text.setText("");
        password_text.setText("");
        String registrati="Registered users: \n";
        String utenti_registrati[] = loginUtenti.RegisteredUsers().split("~");
        for(int i=0; i<utenti_registrati.length;i++){
            String utente_registrato[] = utenti_registrati[i].split("#");
            registrati+="@"+utente_registrato[1]+"\n";
        }
        registeredUserList.setText(registrati);
        }
    }//GEN-LAST:event_registerActionPerformed

    private void userName_textKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userName_textKeyReleased
        jLabelUsername.setText("");
    }//GEN-LAST:event_userName_textKeyReleased

    private void password_textKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_textKeyReleased
        jLabelPassword.setText("");
    }//GEN-LAST:event_password_textKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginUtentiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginUtentiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginUtentiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginUtentiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginUtentiGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel message;
    private javax.swing.JLabel password_label;
    private javax.swing.JPasswordField password_text;
    private javax.swing.JButton register;
    private javax.swing.JCheckBox showPassword;
    private javax.swing.JButton submit;
    private javax.swing.JTextField userName_text;
    private javax.swing.JLabel user_label;
    // End of variables declaration//GEN-END:variables
}
